+incdir+$PRJ_ROOT/output/ip/apb_subsystem/i2c
+incdir+$PRJ_ROOT/output/ip/apb_subsystem/qspi
+incdir+$PRJ_ROOT/output/ip/apb_subsystem/uart

$PRJ_ROOT/output/ip/include/ahb2apb_defines.v
$PRJ_ROOT/output/ip/include/SoC_amba-defines.v
$PRJ_ROOT/output/ip/pad/TPPADLRCMCUDB.v
$PRJ_ROOT/output/ip/pad/pin_mux_rf.v
$PRJ_ROOT/output/ip/pad/gnrl_io_pad.v
$PRJ_ROOT/output/ip/pad/pin_mux.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/i2c/i2c_master_defines.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/i2c/i2c_master_byte_ctrl.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/i2c/timescale.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/i2c/i2c_master_top.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/i2c/i2c_master_bit_ctrl.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/ahb2apb/ahb2apb.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/apb_subsystem.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/qspi/spi_master_fifo.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/qspi/spi_master_tx.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/qspi/spi_master_clkgen.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/qspi/spi_master_apb_if.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/qspi/spi_master_controller.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/qspi/spi_master_rx.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/qspi/apb_spi_master.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/uart/uart_defines.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/uart/raminfr_hubing.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/uart/uart_apb.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/uart/uart_rfifo_hubing.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/uart/uart_transmitter.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/uart/uart_sync_flops.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/uart/uart_tfifo_hubing.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/uart/uart_receiver.v
$PRJ_ROOT/output/ip/apb_subsystem/rtl/pwm/pwm_apb.sv
$PRJ_ROOT/output/ip/apb_subsystem/rtl/pwm/pwm.sv
