$PRJ_ROOT/../ibex/dv/uvm/core_ibex/common/prim/prim_pkg.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_22_16_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_22_16_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_64_57_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_64_57_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_adv.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_scr.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_ram_1p.sv
$PRJ_ROOT/../ibex/dv/uvm/core_ibex/common/prim/prim_ram_1p.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_clock_gating.sv
$PRJ_ROOT/../ibex/dv/uvm/core_ibex/common/prim/prim_clock_gating.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_buf.sv
$PRJ_ROOT/../ibex/dv/uvm/core_ibex/common/prim/prim_buf.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_clock_mux2.sv
$PRJ_ROOT/../ibex/dv/uvm/core_ibex/common/prim/prim_clock_mux2.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_flop.sv
$PRJ_ROOT/../ibex/dv/uvm/core_ibex/common/prim/prim_flop.sv

// Shared lowRISC code
+incdir+$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_assert.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_prince.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_subst_perm.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_28_22_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_28_22_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_72_64_enc.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_72_64_dec.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_check.sv
$PRJ_ROOT/../ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi_pkg.sv


