//==================================================
// This file contains the Excluded objects
// Generated By User: root
// Format Version: 2
// Date: Sat Apr 15 15:45:50 2023
// ExclMode: default
//==================================================
CHECKSUM: "655040205 763566956"
INSTANCE: qspi_tb_top.dut.u_rxfifo
Block 4 "262755815" "elements <= 0;"
Block 19 "2972807468" "pointer_out <= 0;"
Block 27 "2036585465" "pointer_out <= 0;"
CHECKSUM: "3768778099 2244003603"
INSTANCE: qspi_tb_top.dut.u_spictrl.u_rxreg
Block 15 "1041166764" "rx_NS = WAIT_FIFO_DONE;"
Block 18 "2051149688" "clk_en_o = 1'b0;"
Block 22 "118569539" "data_valid = 1'b1;"
Block 23 "858427511" "rx_NS = IDLE;"
Block 25 "1422896571" "data_valid = 1'b1;"
Block 26 "2675116140" "rx_NS = RECEIVE;"
CHECKSUM: "790607765 2214771741"
INSTANCE: qspi_tb_top.dut.u_spictrl
Block 46 "1853902745" "state_next = IDLE;"
Block 48 "3476185555" "spi_status[3] = 1'b1;"
Block 54 "2420326735" "eot = 1'b1;"
Block 62 "1935457114" "spi_status[6] = 1'b1;"
Block 63 "1997462463" "eot = 1'b1;"
Block 64 "3468353484" "state_next = WAIT_EDGE;"
CHECKSUM: "655040205 763566956"
INSTANCE: qspi_tb_top.dut.u_txfifo
Block 4 "262755815" "elements <= 0;"
Block 19 "2972807468" "pointer_out <= 0;"
CHECKSUM: "2102309948 3457403237"
MODULE: qspi_device
Block 80 "2661976576" ";"
CHECKSUM: "1371350343 642971348"
covergroup $unit::qspi_fun_cov::cov_qspi
	coveritem "cp_command_cmd_width"
		bins {{"PAGE_PROGRAMMING","READ_DATA","WRITE_DISABLE","WRITE_ENABLE"}, {"command_width_zero"}}
	coveritem "cp_command_data_width"
		bins {{"WRITE_DISABLE","WRITE_ENABLE"}, {"data_width_128bit","data_width_64bit"}}
